project:
  type: book

book:
  title: "OMOP Radiology"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/omop-radio
  site-url: https://omop-radio-lightbridge.netlify.app
  chapters:
    - index.qmd
    - references.qmd
    - "contents/overview-mi-cdm.qmd"
    - part: Mapping by project
      chapters: 
        - "contents/project/stroke_mapping.qmd"
        - "contents/project/map_birads_composition.qmd"
    - part: Mapping by Variable
      chapters: 
        - "contents/map_age.qmd"
        - "contents/map_sex.qmd"
    - part: Map by table
      chapters: 
        - "contents/map_table/map_procedure_occ_row.qmd"
        - "contents/map_table/map_image_feature.qmd"
    - part: Concept
      chapters: 
        - "contents/concept/omop_image_feature_event.qmd"
    - part: Discuss
      chapters: 
        - "contents/discuss/omop-for-research.qmd"


bibliography: references.bib

format:
  html:
    theme:
      light:
      - cosmo
      - brand
      dark: 
      - darkly
    toc-depth: 4

freeze: auto
